[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --omit=dev --no-audit --no-fund --prefer-offline --no-optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "nginx -g 'daemon off;'"

[variables]
NODE_ENV = "production"
