[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install --no-audit --no-fund --prefer-offline --no-optional"
]

[phases.build]
cmds = [
  "export NODE_OPTIONS='--max-old-space-size=4096'",
  "export NEXT_TELEMETRY_DISABLED=1",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NODE_OPTIONS = "--max-old-space-size=4096"
